#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "BinaryData.h"   // generated by juce_add_binary_data from chobits.jpg

//==============================================================================
// Palette — sampled directly from the Chobits wallpaper image
const juce::Colour ChobitsLookAndFeel::bgDeep         = juce::Colour (0xff17092b);
const juce::Colour ChobitsLookAndFeel::bgMid           = juce::Colour (0xff2d1b5e);
const juce::Colour ChobitsLookAndFeel::starGold         = juce::Colour (0xffffd700);
const juce::Colour ChobitsLookAndFeel::pinkAccent       = juce::Colour (0xffff6b9d);
const juce::Colour ChobitsLookAndFeel::silhouetteBlue   = juce::Colour (0xff3a4a7a);
const juce::Colour ChobitsLookAndFeel::hairGold         = juce::Colour (0xffe8c56d);
const juce::Colour ChobitsLookAndFeel::panelFill        = juce::Colour (0xcc0d0620); // dark translucent

//==============================================================================
ChobitsLookAndFeel::ChobitsLookAndFeel()
{
    setColour (juce::Slider::rotarySliderFillColourId,    starGold);
    setColour (juce::Slider::rotarySliderOutlineColourId, bgMid);
    setColour (juce::Slider::thumbColourId,               pinkAccent);
    setColour (juce::Slider::textBoxTextColourId,         hairGold);
    setColour (juce::Slider::textBoxBackgroundColourId,   juce::Colours::transparentBlack);
    setColour (juce::Slider::textBoxOutlineColourId,      juce::Colours::transparentBlack);
    setColour (juce::ComboBox::backgroundColourId,        panelFill);
    setColour (juce::ComboBox::outlineColourId,           pinkAccent);
    setColour (juce::ComboBox::textColourId,              starGold);
    setColour (juce::ComboBox::arrowColourId,             starGold);
    setColour (juce::PopupMenu::backgroundColourId,       bgDeep);
    setColour (juce::PopupMenu::textColourId,             starGold);
    setColour (juce::PopupMenu::highlightedBackgroundColourId, bgMid);
    setColour (juce::PopupMenu::highlightedTextColourId,  pinkAccent);
    setColour (juce::TextButton::buttonColourId,          panelFill);
    setColour (juce::TextButton::buttonOnColourId,        pinkAccent.withAlpha (0.8f));
    setColour (juce::TextButton::textColourOffId,         hairGold);
    setColour (juce::TextButton::textColourOnId,          juce::Colours::white);
    setColour (juce::ToggleButton::tickColourId,          pinkAccent);
    setColour (juce::ToggleButton::tickDisabledColourId,  bgMid);
    setColour (juce::Label::textColourId,                 hairGold);
    setColour (juce::Label::backgroundColourId,           juce::Colours::transparentBlack);
}

//==============================================================================
void ChobitsLookAndFeel::drawRotarySlider (juce::Graphics& g,
    int x, int y, int width, int height,
    float sliderPos, float startAngle, float endAngle,
    juce::Slider& /*slider*/)
{
    float cx = x + width  * 0.5f;
    float cy = y + height * 0.5f;
    float r  = juce::jmin (width, height) * 0.40f;

    // Dark translucent backing disc
    g.setColour (panelFill.withAlpha (0.82f));
    g.fillEllipse (cx - r, cy - r, r * 2.0f, r * 2.0f);

    // Outer ring
    g.setColour (bgMid.withAlpha (0.9f));
    g.drawEllipse (cx - r - 1, cy - r - 1, (r + 1) * 2.0f, (r + 1) * 2.0f, 1.5f);

    // Fill arc (gold)
    float angle = startAngle + sliderPos * (endAngle - startAngle);
    {
        juce::Path arc;
        arc.addArc (cx - r, cy - r, r * 2.0f, r * 2.0f, startAngle, angle, true);
        g.setColour (starGold.withAlpha (0.9f));
        g.strokePath (arc, juce::PathStrokeType (3.2f, juce::PathStrokeType::curved,
                                                  juce::PathStrokeType::rounded));
    }

    // Pink highlight near thumb tip
    {
        juce::Path hi;
        float span = 0.22f;
        hi.addArc (cx - r * 0.88f, cy - r * 0.88f, r * 1.76f, r * 1.76f,
                   angle - span, angle + span, true);
        g.setColour (pinkAccent.withAlpha (0.55f));
        g.strokePath (hi, juce::PathStrokeType (1.8f));
    }

    // Inner soft glow
    {
        juce::ColourGradient glow (hairGold.withAlpha (0.25f), cx, cy,
                                    bgDeep.withAlpha (0.0f),
                                    cx + r * 0.6f, cy + r * 0.6f, true);
        g.setGradientFill (glow);
        g.fillEllipse (cx - r * 0.6f, cy - r * 0.6f, r * 1.2f, r * 1.2f);
    }

    // Thumb dot
    float tx = cx + r * 0.80f * std::sin (angle);
    float ty = cy - r * 0.80f * std::cos (angle);
    g.setColour (pinkAccent);
    g.fillEllipse (tx - 4.5f, ty - 4.5f, 9.0f, 9.0f);
    g.setColour (juce::Colours::white.withAlpha (0.85f));
    g.fillEllipse (tx - 2.0f, ty - 2.0f, 4.0f, 4.0f);

    // Star sparkle when value is high
    if (sliderPos > 0.75f)
    {
        float alpha = (sliderPos - 0.75f) / 0.25f;
        g.setColour (starGold.withAlpha (alpha * 0.65f));
        for (int i = 0; i < 5; ++i)
        {
            float a = tx + 11.0f * std::cos (i * juce::MathConstants<float>::twoPi / 5.0f);
            float b = ty + 11.0f * std::sin (i * juce::MathConstants<float>::twoPi / 5.0f);
            g.drawLine (tx, ty, a, b, 1.2f);
        }
    }
}

//==============================================================================
void ChobitsLookAndFeel::drawButtonBackground (juce::Graphics& g, juce::Button& btn,
    const juce::Colour&, bool highlighted, bool down)
{
    auto b = btn.getLocalBounds().toFloat().reduced (1.0f);
    juce::Colour fill = down       ? pinkAccent.withAlpha (0.85f)
                       : highlighted ? bgMid.brighter (0.15f)
                                     : panelFill;
    g.setColour (fill);
    g.fillRoundedRectangle (b, 5.0f);

    juce::Colour border = btn.getToggleState() ? pinkAccent : starGold.withAlpha (0.5f);
    g.setColour (border);
    g.drawRoundedRectangle (b, 5.0f, 1.3f);

    if (btn.getToggleState())
    {
        juce::ColourGradient glow (pinkAccent.withAlpha (0.25f), b.getCentreX(), b.getCentreY(),
                                    pinkAccent.withAlpha (0.0f),  b.getRight(),   b.getBottom(), true);
        g.setGradientFill (glow);
        g.fillRoundedRectangle (b, 5.0f);
    }
}

void ChobitsLookAndFeel::drawButtonText (juce::Graphics& g, juce::TextButton& btn,
    bool, bool)
{
    g.setColour (btn.getToggleState() ? juce::Colours::white : hairGold);
    g.setFont (juce::Font ("Georgia", 10.5f, juce::Font::bold));
    g.drawFittedText (btn.getButtonText(), btn.getLocalBounds(),
                      juce::Justification::centred, 1);
}

void ChobitsLookAndFeel::drawComboBox (juce::Graphics& g, int w, int h,
    bool, int, int, int, int, juce::ComboBox&)
{
    auto b = juce::Rectangle<float> (0, 0, (float)w, (float)h);
    g.setColour (panelFill.withAlpha (0.88f));
    g.fillRoundedRectangle (b, 5.0f);
    g.setColour (pinkAccent.withAlpha (0.7f));
    g.drawRoundedRectangle (b.reduced (0.5f), 5.0f, 1.3f);

    // Arrow
    juce::Path arrow;
    float ax = w - 13.0f, ay = h * 0.5f - 3.0f;
    arrow.addTriangle (ax, ay, ax + 7.0f, ay, ax + 3.5f, ay + 5.5f);
    g.setColour (starGold);
    g.fillPath (arrow);
}

void ChobitsLookAndFeel::drawLabel (juce::Graphics& g, juce::Label& label)
{
    g.fillAll (label.findColour (juce::Label::backgroundColourId));
    if (!label.isBeingEdited())
    {
        auto alpha = label.isEnabled() ? 1.0f : 0.5f;
        g.setColour (hairGold.withMultipliedAlpha (alpha));
        g.setFont (label.getFont());
        g.drawFittedText (label.getText(),
                          getLabelBorderSize (label).subtractedFrom (label.getLocalBounds()),
                          label.getJustificationType(), 2,
                          label.getMinimumHorizontalScale());
    }
}

//==============================================================================
//==============================================================================
// EDITOR
//==============================================================================
//==============================================================================

// Helper: set up a rotary knob
static void initKnob (juce::Slider& s)
{
    s.setSliderStyle (juce::Slider::RotaryVerticalDrag);
    s.setTextBoxStyle (juce::Slider::TextBoxBelow, false, 52, 13);
    s.setColour (juce::Slider::textBoxTextColourId,       ChobitsLookAndFeel::hairGold);
    s.setColour (juce::Slider::textBoxBackgroundColourId, juce::Colours::transparentBlack);
    s.setColour (juce::Slider::textBoxOutlineColourId,    juce::Colours::transparentBlack);
}

static void initLabel (juce::Label& l, const juce::String& text)
{
    l.setText (text, juce::dontSendNotification);
    l.setFont (juce::Font ("Georgia", 9.5f, juce::Font::plain));
    l.setJustificationType (juce::Justification::centred);
    l.setColour (juce::Label::textColourId,       ChobitsLookAndFeel::hairGold);
    l.setColour (juce::Label::backgroundColourId, juce::Colours::transparentBlack);
}

static void addVowels (juce::ComboBox& box)
{
    box.addItem ("A  (father)", 1);
    box.addItem ("E  (bed)",    2);
    box.addItem ("I  (feet)",   3);
    box.addItem ("O  (go)",     4);
    box.addItem ("U  (boot)",   5);
}

//==============================================================================
PersoFormantAudioProcessorEditor::PersoFormantAudioProcessorEditor (
    PersoFormantAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
{
    setLookAndFeel (&laf);

    // ---- Load background image from BinaryData ----
    bgImage = juce::ImageCache::getFromMemory (BinaryData::chobits_jpg,
                                               BinaryData::chobits_jpgSize);

    // Plugin size: match image aspect 1280x960, scaled to 900x420
    setSize (900, 420);
    setResizable (false, false);

    // ---- Knobs ----
    for (auto* s : { &morphSlider, &lfoRateSlider, &lfoDepthSlider,
                     &envThreshSlider, &envDepthSlider,
                     &driveSlider, &panSlider, &gainSlider, &mixSlider })
        initKnob (*s);

    addAndMakeVisible (morphSlider);
    addAndMakeVisible (lfoRateSlider);
    addAndMakeVisible (lfoDepthSlider);
    addAndMakeVisible (envThreshSlider);
    addAndMakeVisible (envDepthSlider);
    addAndMakeVisible (driveSlider);
    addAndMakeVisible (panSlider);
    addAndMakeVisible (gainSlider);
    addAndMakeVisible (mixSlider);

    // ---- Labels ----
    initLabel (morphLabel,     "MORPH");
    initLabel (lfoRateLabel,   "LFO RATE");
    initLabel (lfoDepthLabel,  "LFO DEPTH");
    initLabel (envThreshLabel, "THRESHOLD");
    initLabel (envDepthLabel,  "ENV DEPTH");
    initLabel (driveLabel,     "DRIVE");
    initLabel (panLabel,       "PAN");
    initLabel (gainLabel,      "GAIN");
    initLabel (mixLabel,       "MIX");
    initLabel (vowel1Label,    "VOWEL 1");
    initLabel (vowel2Label,    "VOWEL 2");
    initLabel (genderLabel,    "GENDER");
    initLabel (lfoSyncLabel,   "BPM SYNC");

    for (auto* l : { &morphLabel, &lfoRateLabel, &lfoDepthLabel,
                     &envThreshLabel, &envDepthLabel,
                     &driveLabel, &panLabel, &gainLabel, &mixLabel,
                     &vowel1Label, &vowel2Label, &genderLabel, &lfoSyncLabel })
        addAndMakeVisible (*l);

    // ---- ComboBoxes ----
    addVowels (vowel1Box); vowel1Box.setSelectedId (1);
    addVowels (vowel2Box); vowel2Box.setSelectedId (3);
    genderBox.addItem (juce::CharPointer_UTF8 ("\xe2\x99\x82  Masculine"), 1);
    genderBox.addItem (juce::CharPointer_UTF8 ("\xe2\x9c\xa6  Neutral"),   2);
    genderBox.addItem (juce::CharPointer_UTF8 ("\xe2\x99\x80  Feminine"),  3);
    genderBox.setSelectedId (2);
    addAndMakeVisible (vowel1Box);
    addAndMakeVisible (vowel2Box);
    addAndMakeVisible (genderBox);

    // ---- Sync button ----
    lfoSyncButton.setButtonText ("SYNC");
    lfoSyncButton.setClickingTogglesState (true);
    addAndMakeVisible (lfoSyncButton);

    // ---- Title / vendor ----
    titleLabel.setText  ("PersoFormant",   juce::dontSendNotification);
    vendorLabel.setText ("by  Chobits",    juce::dontSendNotification);
    titleLabel .setFont (juce::Font ("Georgia", 26.0f, juce::Font::bold | juce::Font::italic));
    vendorLabel.setFont (juce::Font ("Georgia", 11.0f, juce::Font::italic));
    titleLabel .setJustificationType (juce::Justification::centred);
    vendorLabel.setJustificationType (juce::Justification::centred);
    titleLabel .setColour (juce::Label::textColourId, ChobitsLookAndFeel::starGold);
    vendorLabel.setColour (juce::Label::textColourId, ChobitsLookAndFeel::pinkAccent);
    for (auto* l : { &titleLabel, &vendorLabel })
    {
        l->setColour (juce::Label::backgroundColourId, juce::Colours::transparentBlack);
        addAndMakeVisible (*l);
    }

    // ---- APVTS Attachments ----
    morphAtt     = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "morph",      morphSlider);
    lfoRateAtt   = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "lfoRate",    lfoRateSlider);
    lfoDepthAtt  = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "lfoDepth",   lfoDepthSlider);
    envThreshAtt = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "envThresh",  envThreshSlider);
    envDepthAtt  = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "envDepth",   envDepthSlider);
    driveAtt     = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "drive",      driveSlider);
    panAtt       = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "pan",        panSlider);
    gainAtt      = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "gain",       gainSlider);
    mixAtt       = std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>  (audioProcessor.apvts, "mix",        mixSlider);
    vowel1Att    = std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(audioProcessor.apvts, "vowel1",     vowel1Box);
    vowel2Att    = std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(audioProcessor.apvts, "vowel2",     vowel2Box);
    genderAtt    = std::make_unique<juce::AudioProcessorValueTreeState::ComboBoxAttachment>(audioProcessor.apvts, "genderShift",genderBox);
    lfoSyncAtt   = std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>  (audioProcessor.apvts, "lfoSync",    lfoSyncButton);

    // Star burst on every knob turn
    auto attachBurst = [this](juce::Slider& s)
    {
        s.onValueChange = [this, &s]
        {
            spawnStars (4, s.getBounds().getCentreX() + 0.0f,
                            s.getBounds().getCentreY() + 0.0f);
        };
    };
    for (auto* s : { &morphSlider, &lfoRateSlider, &lfoDepthSlider,
                     &envThreshSlider, &envDepthSlider,
                     &driveSlider, &panSlider, &gainSlider, &mixSlider })
        attachBurst (*s);

    vowel1Box.onChange = [this]{ spawnStars (8, (float)vowel1Box.getBounds().getCentreX(), (float)vowel1Box.getBounds().getCentreY()); };
    vowel2Box.onChange = [this]{ spawnStars (8, (float)vowel2Box.getBounds().getCentreX(), (float)vowel2Box.getBounds().getCentreY()); };

    startTimerHz (60);
}

PersoFormantAudioProcessorEditor::~PersoFormantAudioProcessorEditor()
{
    stopTimer();
    setLookAndFeel (nullptr);
}

//==============================================================================
void PersoFormantAudioProcessorEditor::timerCallback()
{
    animPhase += 0.018f;
    if (animPhase > juce::MathConstants<float>::twoPi)
        animPhase -= juce::MathConstants<float>::twoPi;

    // Update particles
    for (auto& p : particles)
    {
        p.x    += std::cos (p.angle) * p.speed;
        p.y    += std::sin (p.angle) * p.speed - 0.35f;
        p.life -= 0.022f;
        p.opacity = juce::jmax (0.0f, p.life);
    }
    particles.erase (std::remove_if (particles.begin(), particles.end(),
        [](const StarParticle& s){ return s.life <= 0.0f; }), particles.end());

    // Envelope burst
    float env = audioProcessor.getEnvelopeLevel();
    bool trig  = env > 0.05f;
    if (trig && !lastEnvTrig && (int)particles.size() < 50)
        spawnStars (6, getWidth() * 0.5f, getHeight() * 0.35f);
    lastEnvTrig = trig;

    repaint();
}

//==============================================================================
void PersoFormantAudioProcessorEditor::spawnStars (int count, float cx, float cy)
{
    for (int i = 0; i < count; ++i)
    {
        StarParticle p;
        p.x     = cx;
        p.y     = cy;
        p.size  = rng.nextFloat() * 7.5f + 3.0f;
        p.speed = rng.nextFloat() * 2.2f + 0.6f;
        p.angle = rng.nextFloat() * juce::MathConstants<float>::twoPi;
        p.life  = 1.0f;
        p.opacity = 1.0f;
        particles.push_back (p);
    }
}

//==============================================================================
void PersoFormantAudioProcessorEditor::drawStarShape (juce::Graphics& g,
    float cx, float cy, float r, float opacity, juce::Colour col, int pts)
{
    juce::Path star;
    float inner = r * 0.42f;
    for (int i = 0; i < pts * 2; ++i)
    {
        float a   = i * juce::MathConstants<float>::pi / pts
                    - juce::MathConstants<float>::halfPi;
        float rad = (i % 2 == 0) ? r : inner;
        float px  = cx + rad * std::cos (a);
        float py  = cy + rad * std::sin (a);
        if (i == 0) star.startNewSubPath (px, py);
        else         star.lineTo (px, py);
    }
    star.closeSubPath();
    g.setColour (col.withAlpha (opacity));
    g.fillPath  (star);
    g.setColour (col.brighter (0.4f).withAlpha (opacity * 0.4f));
    g.strokePath(star, juce::PathStrokeType (0.7f));
}

//==============================================================================
void PersoFormantAudioProcessorEditor::drawPanel (juce::Graphics& g,
    juce::Rectangle<float> b, const juce::String& title, juce::Colour accent)
{
    // Frosted-glass panel over the image
    g.setColour (ChobitsLookAndFeel::panelFill.withAlpha (0.75f));
    g.fillRoundedRectangle (b, 7.0f);

    g.setColour (accent.withAlpha (0.45f));
    g.drawRoundedRectangle (b.reduced (0.5f), 7.0f, 1.3f);

    // Subtle top accent bar
    juce::Rectangle<float> bar (b.getX(), b.getY(), b.getWidth(), 3.0f);
    g.setColour (accent.withAlpha (0.6f));
    g.fillRect (bar.withTrimmedLeft (7.0f).withTrimmedRight (7.0f));

    // Title text inside panel
    g.setFont (juce::Font ("Georgia", 9.0f, juce::Font::bold));
    g.setColour (accent.withAlpha (0.85f));
    g.drawText (title, (int)b.getX(), (int)b.getY() + 5,
                (int)b.getWidth(), 12, juce::Justification::centred);
}

//==============================================================================
void PersoFormantAudioProcessorEditor::drawEnvelopeMeter (juce::Graphics& g)
{
    float env   = audioProcessor.getEnvelopeLevel();
    float mH    = 70.0f, mW = 7.0f;
    float mx    = 10.0f, my = 175.0f;

    g.setColour (ChobitsLookAndFeel::bgDeep.withAlpha (0.7f));
    g.fillRoundedRectangle (mx, my, mW, mH, 3.0f);
    g.setColour (ChobitsLookAndFeel::pinkAccent.withAlpha (0.35f));
    g.drawRoundedRectangle (mx, my, mW, mH, 3.0f, 1.0f);

    float fillH = juce::jlimit (0.0f, mH, env * mH * 7.0f);
    if (fillH > 0.5f)
    {
        juce::ColourGradient fill (ChobitsLookAndFeel::pinkAccent, mx, my + mH,
                                    ChobitsLookAndFeel::starGold, mx, my, false);
        g.setGradientFill (fill);
        g.fillRoundedRectangle (mx, my + mH - fillH, mW, fillH, 3.0f);
    }
    g.setColour (ChobitsLookAndFeel::hairGold.withAlpha (0.55f));
    g.setFont (juce::Font ("Georgia", 7.5f, juce::Font::plain));
    g.drawText ("ENV", (int)mx - 1, (int)(my + mH) + 2, 10, 10, juce::Justification::centred);
}

//==============================================================================
void PersoFormantAudioProcessorEditor::drawLfoIndicator (juce::Graphics& g)
{
    // Small rotating star to show LFO is alive
    float phase = audioProcessor.getLfoPhase();
    float cx = 465.0f, cy = 280.0f, r = 9.0f;

    juce::Path ring;
    ring.addArc (cx - r, cy - r, r * 2.0f, r * 2.0f, 0, phase, true);
    g.setColour (ChobitsLookAndFeel::starGold.withAlpha (0.65f));
    g.strokePath (ring, juce::PathStrokeType (2.2f));

    float dotX = cx + r * std::cos (phase - juce::MathConstants<float>::halfPi);
    float dotY = cy + r * std::sin (phase - juce::MathConstants<float>::halfPi);
    g.setColour (ChobitsLookAndFeel::pinkAccent);
    g.fillEllipse (dotX - 3.0f, dotY - 3.0f, 6.0f, 6.0f);
}

//==============================================================================
void PersoFormantAudioProcessorEditor::paint (juce::Graphics& g)
{
    int W = getWidth(), H = getHeight();

    // ---- 1. Draw the actual Chobits image as full background ----
    if (bgImage.isValid())
    {
        float imgW = (float)bgImage.getWidth();
        float imgH = (float)bgImage.getHeight();
        float scaleX = W / imgW;
        float scaleY = H / imgH;
        float scale  = juce::jmax (scaleX, scaleY);

        int drawW = juce::roundToInt (imgW * scale);
        int drawH = juce::roundToInt (imgH * scale);
        int offX  = (W - drawW) / 2;
        // Bias upward slightly so we see Chi and the stars, less road
        int offY  = (H - drawH) / 3;

        g.drawImage (bgImage, offX, offY, drawW, drawH,
                     0, 0, bgImage.getWidth(), bgImage.getHeight());

        // Light dark-vignette so panels are readable
        juce::ColourGradient vignette (juce::Colours::transparentBlack, W * 0.5f, H * 0.5f,
                                        juce::Colours::black.withAlpha (0.55f), 0, 0, true);
        g.setGradientFill (vignette);
        g.fillRect (0, 0, W, H);
    }
    else
    {
        // Fallback gradient if image didn't load
        juce::ColourGradient sky (ChobitsLookAndFeel::bgDeep, 0, 0,
                                   ChobitsLookAndFeel::bgMid, (float)W, (float)H, false);
        g.setGradientFill (sky);
        g.fillRect (0, 0, W, H);
    }

    // ---- 2. Draw panel backgrounds (frosted glass over the image) ----
    drawPanel (g, juce::Rectangle<float>(8,  8, 195, 260),
               "VOWEL  MORPH", ChobitsLookAndFeel::pinkAccent);

    drawPanel (g, juce::Rectangle<float>(210, 8, 160, 175),
               "LFO", ChobitsLookAndFeel::starGold);

    drawPanel (g, juce::Rectangle<float>(378, 8, 160, 175),
               "ENV  SYNC", ChobitsLookAndFeel::pinkAccent);

    drawPanel (g, juce::Rectangle<float>(546, 8, 346, 260),
               "TONE  &  OUTPUT", ChobitsLookAndFeel::hairGold);

    // ---- 3. Floating star particles ----
    for (auto& p : particles)
    {
        juce::Colour col = ChobitsLookAndFeel::starGold
            .interpolatedWith (ChobitsLookAndFeel::pinkAccent, 1.0f - p.life);
        drawStarShape (g, p.x, p.y, p.size, p.opacity, col, 5);
    }

    // ---- 4. Animated ambient stars over the image sky area ----
    struct AmbStar { float x, y, r; };
    static const AmbStar amb[] = {
        {55,35,7},{130,18,5},{280,22,8},{420,14,6},
        {590,30,7},{700,10,5},{820,28,8},{880,18,6},
        {170,60,5},{360,70,6},{660,55,7},
    };
    for (auto& s : amb)
    {
        float pulse = 0.65f + 0.35f * std::sin (animPhase + s.x * 0.012f);
        drawStarShape (g, s.x, s.y, s.r * pulse, 0.70f * pulse,
                       ChobitsLookAndFeel::starGold, 5);
    }

    // ---- 5. Envelope meter & LFO ring ----
    drawEnvelopeMeter (g);
    drawLfoIndicator  (g);

    // ---- 6. Title overlay ----
    {
        juce::ColourGradient glow (ChobitsLookAndFeel::pinkAccent.withAlpha (0.18f),
                                    W * 0.5f, (float)(H - 60),
                                    juce::Colours::transparentBlack,
                                    W * 0.5f, (float)(H - 20), false);
        g.setGradientFill (glow);
        g.fillRect (230, H - 75, 440, 55);
    }
}

//==============================================================================
void PersoFormantAudioProcessorEditor::resized()
{
    int W = getWidth();
    int H = getHeight();
    juce::ignoreUnused (W, H);

    // ---- Title / vendor ----
    titleLabel .setBounds (270, getHeight() - 68, 360, 32);
    vendorLabel.setBounds (270, getHeight() - 38, 360, 18);

    // ============================================================
    // VOWEL MORPH section  (panel: x=8, y=8, w=195, h=260)
    // ============================================================
    int vx = 12;

    vowel1Label.setBounds (vx,      28, 88, 13);
    vowel1Box  .setBounds (vx,      42, 88, 22);

    vowel2Label.setBounds (vx + 98, 28, 88, 13);
    vowel2Box  .setBounds (vx + 98, 42, 88, 22);

    morphLabel .setBounds (vx + 50, 72, 88, 13);
    morphSlider.setBounds (vx + 38, 84, 112, 112);

    genderLabel.setBounds (vx + 10, 205, 80, 13);
    genderBox  .setBounds (vx +  8, 219, 100, 22);

    // ============================================================
    // LFO section  (panel: x=210, y=8, w=160, h=175)
    // ============================================================
    int lx = 214;

    lfoRateLabel .setBounds (lx,      28, 74, 13);
    lfoRateSlider.setBounds (lx - 2,  40, 80, 88);

    lfoDepthLabel .setBounds (lx + 82, 28, 74, 13);
    lfoDepthSlider.setBounds (lx + 80, 40, 80, 88);

    lfoSyncLabel  .setBounds (lx + 35, 138, 76, 13);
    lfoSyncButton .setBounds (lx + 42, 152, 60, 20);

    // ============================================================
    // ENV SYNC section  (panel: x=378, y=8, w=160, h=175)
    // ============================================================
    int ex = 382;

    envThreshLabel .setBounds (ex,      28, 74, 13);
    envThreshSlider.setBounds (ex - 2,  40, 80, 88);

    envDepthLabel .setBounds (ex + 82, 28, 74, 13);
    envDepthSlider.setBounds (ex + 80, 40, 80, 88);

    // ============================================================
    // OUTPUT section  (panel: x=546, y=8, w=346, h=260)
    // ============================================================
    int ox = 552;

    driveLabel .setBounds (ox,       28, 80, 13);
    driveSlider.setBounds (ox - 3,   40, 88, 90);

    panLabel   .setBounds (ox + 90,  28, 80, 13);
    panSlider  .setBounds (ox + 88,  40, 80, 90);

    gainLabel  .setBounds (ox + 178, 28, 80, 13);
    gainSlider .setBounds (ox + 176, 40, 80, 90);

    mixLabel   .setBounds (ox + 258, 28, 80, 13);
    mixSlider  .setBounds (ox + 255, 40, 88, 90);
}
